[2023-06-02T02:40:50.849+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.transform manual__2023-06-02T02:40:28.344519+00:00 [queued]>
[2023-06-02T02:40:50.872+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.transform manual__2023-06-02T02:40:28.344519+00:00 [queued]>
[2023-06-02T02:40:50.872+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-02T02:40:50.906+0000] {taskinstance.py:1327} INFO - Executing <Task(DockerOperator): transform> on 2023-06-02 02:40:28.344519+00:00
[2023-06-02T02:40:50.915+0000] {standard_task_runner.py:57} INFO - Started process 550 to run task
[2023-06-02T02:40:50.920+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'transform', 'manual__2023-06-02T02:40:28.344519+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmppanauxxl']
[2023-06-02T02:40:50.923+0000] {standard_task_runner.py:85} INFO - Job 67: Subtask transform
[2023-06-02T02:40:51.000+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.transform manual__2023-06-02T02:40:28.344519+00:00 [running]> on host 494051a68f2e
[2023-06-02T02:40:51.168+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-06-02T02:40:28.344519+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-02T02:40:28.344519+00:00'
[2023-06-02T02:40:51.219+0000] {docker.py:324} INFO - Starting docker container from image my_etl:transform
[2023-06-02T02:40:54.282+0000] {docker.py:391} INFO - /app/transform.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_drop['Age'] = df_drop['Age'].astype(int)
[2023-06-02T02:40:54.322+0000] {docker.py:391} INFO - /app/transform.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_drop['Sex'] = df_drop['Sex'].replace(['Female','Girl','f','Man','Male','FM','MF','both','m',''],\
[2023-06-02T02:40:56.924+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=transform, execution_date=20230602T024028, start_date=20230602T024050, end_date=20230602T024056
[2023-06-02T02:40:57.005+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-02T02:40:57.054+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
